<<<<<<< HEAD
title: Hody, folklor a tradice na Podluží (test)
=======
title: Ahoj
>>>>>>> master
baseURL: http://compassionate-sinoussi-0475ea.netlify.com
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

